apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: github-fetch-template
  title: Fetch github Template
  description: Template to fetch a github repo and push to a provided group in the  github instance
spec:
  owner: backstage/scaffolder-core
  type: service

  parameters:
    - title: Repository Information
      required:
        - repoUrl
        - publishUrl
      properties:
        publishUrl:
          title: Destination Repository URL
          type: string
          description: URL of the destination github repository to push to
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        
        repoUrl:
          title: Source Repository URL
          type: string
          description: URL of the source github repository to fetch from

  steps:
    - id: fetch-repo
      name: Fetch github Repo
      action: fetch:plain
      input:
        targetPath: ./
        url: ${{ parameters.repoUrl }}

    - id: acme-file-create
      name: Fetch github Repo
      action: acme:file:create
      input:
        contents: "hello"
        filename: "xyz.yaml"
    - id: publish
      name: Publish to github ()
      action: publish:guthub
      input:
        allowedHosts: ['github.com']
        # repoUrl: github.com/${{ parameters.githubGroup }}/${{ parameters.name }}
        repoUrl: ${{ parameters.publishUrl }}
        defaultBranch: main
        gitCommitMessage: Initial commit for ${{ parameters.name }}


